LDFLAGS= -L${shell root-config --libdir} -L/mnt/research/IceCube/baclark/IceCube/work_with_jorge/comparison_studies
CXXFLAGS= -I${shell root-config --cflags} -I/mnt/research/IceCube/baclark/IceCube/work_with_jorge/comparison_studies
LDLIBS += $(shell root-config --libs) -lAra

